version: '3.8'

services:
  app:
    build:
      context: .
    container_name: micro-cursos-container
    ports:
      - "8082:8082"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-sisdb2025
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sisdb2025
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: